services:
  database:
    image: postgres:15
    env_file:
      - .env.local
    ports:
      - 5433:5432
    volumes:
      - ./db/dumps/dump-public-10-04-24.sql:/docker-entrypoint-initdb.d/dump-public-10-04-24.sql


